name: LoginX
version: '${project.version}'
main: me.abdoabk.loginX.LoginX
api-version: '1.20'
description: Secure Login, Session and Premium Protection Plugin
author: abdoabk
website: https://github.com/abdoabk/LoginX

commands:
  register:
    description: Register an account
    usage: /register <password> <confirm>
    permission: loginx.player
  login:
    description: Login to your account
    usage: /login <password>
    permission: loginx.player
  logout:
    description: Logout from your account
    usage: /logout
    permission: loginx.player
  changepass:
    description: Change your password
    usage: /changepass <oldPassword> <newPassword> <confirm>
    permission: loginx.player
  premium:
    description: Lock your account to your premium Mojang account
    usage: /premium
    permission: loginx.premium
  loginx:
    description: LoginX admin commands
    usage: /loginx <reload|info|session|premium>
    permission: loginx.admin

permissions:
  loginx.player:
    description: Basic player authentication commands
    default: true
  loginx.premium:
    description: Access to /premium command
    default: true
  loginx.admin:
    description: Full admin access to LoginX
    default: op
  loginx.bypass:
    description: Bypass authentication (e.g. for admins)
    default: false